version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
          - /db/:/var/lib/postgresql/data
    environment:
       
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD : password
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"